import type { Metadata } from "next";
import Link from "next/link";
import { buildComplianceReview } from "@/lib/compliance-engine";
import { resolveProductInput } from "@/lib/product-resolver";
import {
  buildCheckParams,
  CheckQueryInput,
  parseCheckFacts,
} from "@/lib/check-query";
import ReportToolbar from "./ReportToolbar";

export const metadata: Metadata = {
  title: "Product Compliance Screening Report | SellComply",
  description:
    "Shareable and printable product compliance screening report generated by SellComply.",
  robots: { index: false, follow: false },
};

const statusLabel = {
  required: "REQUIRED",
  likely: "LIKELY",
  verify: "VERIFY",
  platform: "PLATFORM",
} as const;

function reportId(value: string) {
  let hash = 2166136261;
  for (let i = 0; i < value.length; i += 1) {
    hash ^= value.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return `SC-${(hash >>> 0).toString(16).toUpperCase().padStart(8, "0")}`;
}

export default async function ReportPage({
  searchParams,
}: {
  searchParams: Promise<CheckQueryInput>;
}) {
  const params = await searchParams;
  const rawProduct = (params.product || "wireless headphones").slice(0, 500);
  const country = params.country || "Germany";
  const marketplace = params.marketplace || "Amazon";
  const facts = parseCheckFacts(params);

  const resolved = await resolveProductInput(rawProduct);
  const result = buildComplianceReview(
    resolved.resolvedText,
    country,
    marketplace,
    facts
  );

  const displayProduct = resolved.title || rawProduct;
  const canonicalQuery = buildCheckParams({
    product: rawProduct,
    country,
    marketplace,
    facts,
  });

  const checkHref = `/check?${canonicalQuery.toString()}`;
  const generatedAt = new Intl.DateTimeFormat("en", {
    year: "numeric",
    month: "short",
    day: "2-digit",
    timeZone: "UTC",
  }).format(new Date());

  const id = reportId(canonicalQuery.toString());

  return (
    <div className="report-page">
      <ReportToolbar checkHref={checkHref} />

      <main className="report-sheet">
        <header className="report-header">
          <div className="report-brand">
            <Link href="/">Sell<span>Comply</span></Link>
            <small>PRODUCT COMPLIANCE SCREENING</small>
          </div>
          <div className="report-meta-top">
            <div><span>REPORT</span><strong>{id}</strong></div>
            <div><span>GENERATED</span><strong>{generatedAt}</strong></div>
          </div>
        </header>

        <section className="report-hero">
          <div>
            <span className="report-eyebrow">COMPLIANCE REPORT</span>
            <h1>{displayProduct}</h1>
            <div className="report-tags">
              <span>{result.market.flag} {result.market.name}</span>
              {result.marketplace && <span>{result.marketplace.name}</span>}
              <span>{result.product.category}</span>
              <span>{result.certainty} classification confidence</span>
            </div>
          </div>

          <div className={`report-risk-card ${result.risk.level}`}>
            <span>SCREENING RISK</span>
            <div>
              <strong>{result.risk.score}</strong>
              <small>/100</small>
            </div>
            <b>{result.risk.label.toUpperCase()}</b>
            <p>{result.risk.summary}</p>
          </div>
        </section>

        {(resolved.brand || resolved.sku || resolved.gtin || resolved.productCategory) && (
          <section className="report-product-data">
            <div className="report-section-title">
              <span>00</span>
              <h2>Product identity</h2>
            </div>
            <div className="report-data-grid">
              {resolved.brand && <div><span>Brand</span><strong>{resolved.brand}</strong></div>}
              {resolved.productCategory && <div><span>Product category</span><strong>{resolved.productCategory}</strong></div>}
              {resolved.sku && <div><span>SKU</span><strong>{resolved.sku}</strong></div>}
              {resolved.gtin && <div><span>GTIN</span><strong>{resolved.gtin}</strong></div>}
              {resolved.sourceUrl && (
                <div className="wide">
                  <span>Source product URL</span>
                  <a href={resolved.sourceUrl} target="_blank" rel="noreferrer">
                    {resolved.sourceUrl}
                  </a>
                </div>
              )}
            </div>
          </section>
        )}

        <section className="report-overview-grid">
          <article>
            <span>REQUIRED</span>
            <strong>{result.summary.required}</strong>
            <p>Matched rule packs marked required for this screening.</p>
          </article>
          <article>
            <span>LIKELY</span>
            <strong>{result.summary.likely}</strong>
            <p>Likely applicable rules that still depend on exact scope.</p>
          </article>
          <article>
            <span>VERIFY</span>
            <strong>{result.summary.verify}</strong>
            <p>Open applicability or transition questions to confirm.</p>
          </article>
          <article>
            <span>RULE PACKS</span>
            <strong>{result.summary.rulesMatched}</strong>
            <p>Structured regulatory rule packs matched.</p>
          </article>
        </section>

        <section className="report-section">
          <div className="report-section-title">
            <span>01</span>
            <h2>Top risk drivers</h2>
          </div>
          <div className="report-risk-list">
            {result.risk.topDrivers.map((factor) => (
              <article key={factor.id}>
                <div>
                  <strong>{factor.label}</strong>
                  <p>{factor.detail}</p>
                </div>
                <span>+{factor.points}</span>
              </article>
            ))}
          </div>
        </section>

        <section className="report-section">
          <div className="report-section-title">
            <span>02</span>
            <h2>Applicable review areas</h2>
          </div>
          <div className="report-rule-list">
            {result.reviewItems.map((item, index) => (
              <article key={item.id}>
                <div className="report-rule-index">
                  {String(index + 1).padStart(2, "0")}
                </div>
                <div className="report-rule-copy">
                  <div className="report-rule-title-row">
                    <h3>{item.title}</h3>
                    <span className={`report-rule-status ${item.status}`}>
                      {statusLabel[item.status]}
                    </span>
                  </div>
                  <p>{item.detail}</p>
                  {item.why && <small><b>Why:</b> {item.why}</small>}
                  {item.effectiveNote && <small>{item.effectiveNote}</small>}
                  {item.sourceUrl && item.sourceLabel && (
                    <a href={item.sourceUrl} target="_blank" rel="noreferrer">
                      {item.sourceLabel} ↗
                    </a>
                  )}
                </div>
              </article>
            ))}
          </div>
        </section>

        <section className="report-section">
          <div className="report-section-title">
            <span>03</span>
            <h2>Evidence checklist</h2>
          </div>
          <div className="report-evidence-grid">
            <article>
              <div className="report-mini-head">
                <span>DOCUMENTS</span>
                <strong>{result.documents.length}</strong>
              </div>
              <ul>
                {result.documents.map((item) => <li key={item}>{item}</li>)}
              </ul>
            </article>
            <article>
              <div className="report-mini-head">
                <span>LABELS & PRODUCT INFO</span>
                <strong>{result.labels.length}</strong>
              </div>
              <ul>
                {result.labels.map((item) => <li key={item}>{item}</li>)}
              </ul>
            </article>
            <article>
              <div className="report-mini-head">
                <span>OPEN QUESTIONS</span>
                <strong>{result.evidenceGaps.length}</strong>
              </div>
              <ul>
                {result.evidenceGaps.map((item) => <li key={item}>{item}</li>)}
              </ul>
            </article>
          </div>
        </section>

        <section className="report-section">
          <div className="report-section-title">
            <span>04</span>
            <h2>Recommended action plan</h2>
          </div>
          <ol className="report-action-list">
            {result.actionPlan.map((item) => <li key={item}>{item}</li>)}
          </ol>
        </section>

        <section className="report-section">
          <div className="report-section-title">
            <span>05</span>
            <h2>Official sources</h2>
          </div>
          <div className="report-source-list">
            {result.officialSources.map((source) => (
              <a href={source.url} target="_blank" rel="noreferrer" key={source.url}>
                <span>OFFICIAL</span>
                <strong>{source.label}</strong>
                <small>{source.url}</small>
              </a>
            ))}
          </div>
        </section>

        <section className="report-section report-uncertainty">
          <div className="report-section-title">
            <span>06</span>
            <h2>Reduce uncertainty</h2>
          </div>
          <ul>
            {result.risk.reducers.map((item) => <li key={item}>{item}</li>)}
          </ul>
        </section>

        <footer className="report-footer">
          <div>
            <strong>SellComply</strong>
            <span>{id}</span>
          </div>
          <p>
            SellComply provides compliance intelligence and workflow guidance,
            not legal advice, certification, approval, or a legal determination.
            Requirements can depend on exact technical characteristics, claims,
            supply-chain role, jurisdiction, effective dates, exemptions and
            current regulator guidance.
          </p>
          <small>
            This shareable URL recreates the screening from the same product,
            market, marketplace and confirmed facts using the current SellComply
            rule set. It is not a frozen regulatory snapshot.
          </small>
        </footer>
      </main>
    </div>
  );
}
